name: NodeJS deployment

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install NPM
      run: npm install
    
    - name: Build
      run: npm run build

    - name: Listing
      run: ls -la

    - name: Delete Existing Files
      run : sudo sshpass -p ${{ secrets.PASSWORD }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'rm -rf ${{ secrets.TARGET }}/*'

    - name: Compress and Copy New Files to server
      run : |
            cd dist/
            tar -czvf ../../compressed.tar.gz ./
            cd ..
            cd ..
            sudo sshpass -p ${{ secrets.PASSWORD }} scp -v -o StrictHostKeyChecking=no -r compress.tar.gz ${{ secrets.USERNAME }}@${{ secrets.HOST }}:{{ secrets.TARGET }}

    - name: Uncompress new Files
      run : sudo sshpass -p ${{ secrets.PASSWORD }} -v ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} 'cd {{ secrets.TARGET }}/ && tar -xzvf compressed.tar.gz && rm compressed.tar.gz'
